### ISSUE TITLE
I can't seem to start it up

### ISSUE THREAD

**Issue by six-shooter** [seldonlabs/OmniScanner#1]
I installed it, and ran the EDMCoverlay.exe from the "C:\Users\jorns\AppData\Local\EDMarketConnector\plugins\OmniScanner\EDMCOverlay" folder as administrator. started EDMC, but it doesn't recognize it :(

Anything I might be doing wrong?

**Comment by seldonlabs** [comment]
Be sure you are running in Borderless or Windowed mode, Fullscreen is not supported.
Also try the latest version 0.2.1

**Comment by six-shooter** [comment]
I fixed it by removing an old version of the edmc-overlay. It worked for a tiny bit. And now I keep getting "BAD REQUEST" instead of information.
I have updated both EDMC and this plugin to the latest versions.
![error](https://user-images.githubusercontent.com/26160046/39546311-3d81b590-4e54-11e8-8cc6-165c0e251d6b.jpg)

update: Delved into the code a bit: it says HTTPerror that will produce it. and http://cmdrinfo.seldonlabs.com/req is down?

is it just that and do I just need to wait?

**Comment by seldonlabs** [comment]
Yep, the server went down for some reason. It's up again now.

-EDIT-

I may know why the server went down, I'll apply a server side fix.

**Comment by six-shooter** [comment]
I will check tonight if it works again. if it does, I'll close this issue :)

Is it normal by the way that the overlay causes some visual stutter when active?

PS: Great job on the plugin by the way, very useful!

**Comment by seldonlabs** [comment]
I can't say for sure, I don't have any visual artifacts while using EDMCOverlay, but it could happen that you lose focus of the ED window sometimes, usually when EDMCOverlay writes something on the screen for the first time after opening EDMC.

**Comment by six-shooter** [comment]
I wonder if it is possible to have your plugin without overlay, but show it in the edmc-window. I'd love that as a feature

**Comment by six-shooter** [comment]
You absolute hero! :D You did it within 6 hours of me asking! I am amazed :)

**Comment by seldonlabs** [comment]
Not for now, because Tkinter is a mess, maybe in the future. I'm closing this issue to avoid going off-topic.
